### ISSUE TITLE
Fatal: WP_CLI not found

### ISSUE THREAD

**Issue by Brugman** [boogah/plu-redux#1]
Hi.

I can't install the plugin:

`Fatal error: Uncaught Error: Class "WP_CLI" not found in plu-redux\plu-redux.php:135`

Wrapping line 135 in `if ( class_exists('WP_CLI') )` seems to fix it, but I haven't done any CLI integration yet, so I don't know if that's the recommended method.

WP-CLI still works afterwards.

**Comment by boogah** [comment]
Sorry about that! This has been fixed in version 2.1.1.
